//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FulfillmentProviders.FulfillmentCarrierProviders.Transsmart.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TranssmartFulfillmentCarrierProviderResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranssmartFulfillmentCarrierProviderResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FulfillmentProviders.FulfillmentCarrierProviders.Transsmart.Resources.TranssmartF" +
                            "ulfillmentCarrierProviderResources", typeof(TranssmartFulfillmentCarrierProviderResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Transsmart account to utilize.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Transsmart API endpoint (eg. https://accept-api.transsmart.com).
        /// </summary>
        internal static string ApiEndpoint {
            get {
                return ResourceManager.GetString("ApiEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API password.
        /// </summary>
        internal static string ApiPassword {
            get {
                return ResourceManager.GetString("ApiPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API username (email address).
        /// </summary>
        internal static string ApiUsername {
            get {
                return ResourceManager.GetString("ApiUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mapping configuration for carriers and service levels.
        /// </summary>
        internal static string CarrierMappingConfiguration {
            get {
                return ResourceManager.GetString("CarrierMappingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default package height.
        /// </summary>
        internal static string DefaultHeightWhenNotSpecified {
            get {
                return ResourceManager.GetString("DefaultHeightWhenNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default package length.
        /// </summary>
        internal static string DefaultLengthWhenNotSpecified {
            get {
                return ResourceManager.GetString("DefaultLengthWhenNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default package linear UOM (for height, width and length).
        /// </summary>
        internal static string DefaultLinearUOMWhenNotSpecified {
            get {
                return ResourceManager.GetString("DefaultLinearUOMWhenNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default package weight unit of measure.
        /// </summary>
        internal static string DefaultWeightUOMWhenNotSpecified {
            get {
                return ResourceManager.GetString("DefaultWeightUOMWhenNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default package weight.
        /// </summary>
        internal static string DefaultWeightWhenNotSpecified {
            get {
                return ResourceManager.GetString("DefaultWeightWhenNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default package width.
        /// </summary>
        internal static string DefaultWidthWhenNotSpecified {
            get {
                return ResourceManager.GetString("DefaultWidthWhenNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate return label when available.
        /// </summary>
        internal static string GenerateReturnLabel {
            get {
                return ResourceManager.GetString("GenerateReturnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The residential flag for addresses (STS should be false, SFS should be true).
        /// </summary>
        internal static string IsResidential {
            get {
                return ResourceManager.GetString("IsResidential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transsmart mail type to use when defining addresses (Default 1).
        /// </summary>
        internal static string MailType {
            get {
                return ResourceManager.GetString("MailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapper for linear UOM.
        /// </summary>
        internal static string MapperLinearUOM {
            get {
                return ResourceManager.GetString("MapperLinearUOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapper for package type.
        /// </summary>
        internal static string MapperPackageType {
            get {
                return ResourceManager.GetString("MapperPackageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapper for quantity UOM.
        /// </summary>
        internal static string MapperQuantityUOM {
            get {
                return ResourceManager.GetString("MapperQuantityUOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapper for weight UOM.
        /// </summary>
        internal static string MapperWeightUOM {
            get {
                return ResourceManager.GetString("MapperWeightUOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The override quantity uom to use for line items.
        /// </summary>
        internal static string OverrideQuantityUOM {
            get {
                return ResourceManager.GetString("OverrideQuantityUOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transsmart, easily connect your webshop, ERP and WMS to all your carriers! Control and optimize your shipment handling and transport costs from order entry until delivery. Connect your logistics services to your checkout and ERP/WMS with standard plugins..
        /// </summary>
        internal static string ProviderDescription {
            get {
                return ResourceManager.GetString("ProviderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transsmart.
        /// </summary>
        internal static string ProviderDisplayName {
            get {
                return ResourceManager.GetString("ProviderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default service type to utilize (DOCS, NON-DOCS, ENVELOPE), default of NON-DOCS.
        /// </summary>
        internal static string ServiceType {
            get {
                return ResourceManager.GetString("ServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timeout in seconds to use for the API.
        /// </summary>
        internal static string TimeoutInSeconds {
            get {
                return ResourceManager.GetString("TimeoutInSeconds", resourceCulture);
            }
        }
    }
}
